<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: wardana
 * Date: Fri, 13 May 2022 10:00:43 +0000
 */

$conf['title'] = 'Wardana\'s Wiki';
$conf['template'] = 'vector';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['proxy']['user'] = 'wardana';
$conf['proxy']['pass'] = '<b>QEQwa3V3MWsx';
