# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 13 May 2022 09:40:33 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

wardana:$2y$10$c56RNNhArp3IgcH3ZHSHcu9sJtfwieJ1UG49UUNmjl5SDQTbQL35.:Made Wardana:made.wardana44@gmail.com:admin,user
